var db = require("../models");

function createMock(){
        var mockData = {
        "patients": [
                {"id": 1,
                "name": "Frank Sutton",
                "email": "frank.sutton@example.com",
                "dob": '1979-01-28',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/men/74.jpg"},
                {"id": 2,
                "name": "Philip Prescott",
                "email": "philip.prescott@example.com",
                "dob": '1983-01-02',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/men/34.jpg"},
                {"id": 3,
                "name": "Clyde Kuhn",
                "email": "clyde.kuhn@example.com",
                "dob": '1971-10-21',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/men/43.jpg"},
                {"id": 4,
                "name": "Brooklyn Ellis",
                "email": "brooklyn.ellis@example.com",
                "dob": '1945-08-19',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/women/40.jpg"},
                {"id": 5,
                "name": "Eureka Virginia",
                "email": "eureka.virginia@example.com",
                "dob": '1945-08-19',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/women/41.jpg"},
                {"id": 6,
                "name": "Amee Lee",
                "email": "amee.lee@example.com",
                "dob": '1989-10-01',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/women/10.jpg"},
                {"id": 7,
                "name": "Justin TrueDeau",
                "email": "justin.truedeau@example.com",
                "dob": '1980-10-10',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/men/10.jpg"},
                {"id": 8,
                "name": "Thomas Wayne",
                "email": "thomas.wayne@example.com",
                "dob": '1990-10-12',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/men/30.jpg"},
                {"id": 9,
                "name": "Judith Smith",
                "email": "judith.smith@example.com",
                "dob": '1988-11-29',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/women/20.jpg"},
                {"id": 10,
                "name": "Justine Watt",
                "email": "justine.watt@example.com",
                "dob": '1960-03-12',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/women/5.jpg"},
                {"id": 11,
                "name": "James Charmichael",
                "email": "james.charmichael@example.com",
                "dob": '1987-05-03',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/men/11.jpg"},
                {"id": 12,
                "name": "Jane Jones",
                "email": "jane.jones@example.com",
                "dob": '1990-06-03',
                "notes": "No Problem",
                "picture": "https://randomuser.me/api/portraits/women/17.jpg"},

        ]};

        db.patients.bulkCreate(mockData.patients).then(function(dbExample) {
                console.log(`STORED SAMPLE PATIENTS!!`);
        });

}

module.exports = createMock;
